CREATE SCHEMA IF NOT EXISTS clean;

DROP TABLE IF EXISTS clean.rita;

create table clean.rita (
	year int,
	quarter int,
	month int,
	dayofmonth int,
	dayofweek int,
	flightdate text,
	reporting_airline text,
	dot_id_reporting_airline text,
	iata_code_reporting_airline text,
	tail_number text,
	flight_number_reporting_airline int,
	originairportid text,
	originairportseqid text,
	origincitymarketid text,
	origin text,
	origincityname text,
	originstate text,
	originstatefips text,
	originstatename text,
	originwac text,
	destairportid text,
	destairportseqid text,
	destcitymarketid text,
	dest text,
	destcityname text,
	deststate text,
	deststatefips text,
	deststatename text,
	destwac text,
	crsdeptime text,
	deptime text,
	depdelay float,
	depdelayminutes float,
	depdel15 float,
	departuredelaygroups float,
	deptimeblk text,
	taxiout int,
	wheelsoff text,
	wheelson text,
	taxiin int,
	crsarrtime text,
	arrtime text,
	arrdelay float,
	arrdelayminutes float,
	arrdel15 float,
	arrivaldelaygroups float,
	arrtimeblk text,
	cancelled text,
	diverted text,
	crselapsedtime text,
	actualelapsedtime text,
	airtime text,
	flights text,
	distance text,
	distancegroup text,
	divairportlandings text,
	rangoatrasohoras text
	
);
